apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-to-proxy-nginx
  namespace: ps  # Namespace where your app and proxy-nginx are running
spec:
  podSelector:
    matchLabels:
      app: my-app  # The label of your application pod
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: ps  # The namespace of proxy-nginx
        - podSelector:
            matchLabels:
              app: proxy-nginx  # Label selector for the proxy-nginx pod

