apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: gradual-network-latency
  namespace: nginx-namespace  # Ensure this matches your namespace
spec:
  entry: network-latency-sequence
  templates:
    - name: network-latency-sequence
      templateType: Serial  # Defines sequential execution
      children:
        - block-30ms-latency
        - block-60ms-latency
        - block-90ms-latency
        - block-100ms-latency
        - pod-restart-task  # Added the new pod restart task here

    - name: block-30ms-latency
      templateType: NetworkChaos
      networkChaos:
        action: delay
        mode: all
        selector:
          labelSelectors:
            app: nginx  # Ensure the label matches your app's pods
        delay:
          latency: "10000ms"
          correlation: "30"
          jitter: "0ms"
      deadline: "2m"  # Replacing duration with deadline

    - name: block-60ms-latency
      templateType: NetworkChaos
      networkChaos:
        action: delay
        mode: all
        selector:
          labelSelectors:
            app: nginx
        delay:
          latency: "10000ms"
          correlation: "60"
          jitter: "0ms"
      deadline: "2m"  # Replacing duration with deadline

    - name: block-90ms-latency
      templateType: NetworkChaos
      networkChaos:
        action: delay
        mode: all
        selector:
          labelSelectors:
            app: nginx
        delay:
          latency: "10000ms"
          correlation: "90"
          jitter: "0ms"
      deadline: "2m"  # Replacing duration with deadline

    - name: block-100ms-latency
      templateType: NetworkChaos
      networkChaos:
        action: delay
        mode: all
        selector:
          labelSelectors:
            app: nginx
        delay:
          latency: "10000ms"
          correlation: "100"
          jitter: "0ms"
      deadline: "2m"  # Replacing duration with deadline

    - name: pod-restart-task  # New task for pod restart
      templateType: PodChaos
      podChaos:
        action: pod-kill
        mode: fixed
        value: "1"
        selector:
          namespaces:
            - nginx-namespace
          labelSelectors:
            app: nginx
      deadline: "60s"  # Use deadline instead of duration to specify the chaos duration
