apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-latency
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - bank-of-anthos
    labelSelectors:
      app: ledgerwriter
  delay:
    latency: "100ms"
    correlation: "100"
    jitter: "10ms"

