apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: resource-starvation
  namespace: bank-of-anthos
spec:
  mode: one
  selector:
    namespaces:
      - bank-of-anthos
    labelSelectors:
      app: ledgerwriter
  stressors:
    cpu:
      workers: 4
    memory:
      workers: 5
      size: "150M" # Corrected memory size format
        #  duration: "30s"

