apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-exec-job
  namespace: ps
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: postgres-client
        image: postgres:latest  # PostgreSQL official image
        command:
          - /bin/sh
          - "-c"
          - |
            echo "Extracting sensitive data..."
            PGPASSWORD='root' psql -h postgres -U postgres -d postgres -c "COPY transactions TO '/tmp/transactions.csv' CSV HEADER;"
            echo "Data saved to /tmp/transactions.csv"

