apiVersion: v1
kind: Pod
metadata:
  name: rogue-pod
  namespace: ps
  labels:
    role: attacker
spec:
  containers:
  - name: attacker
    image: alpine
    command: ["/bin/sh", "-c"]
    args:
      - while true; do sleep 30; done;
    securityContext:
      privileged: false  # Ensure it's not privileged
  restartPolicy: Never

