apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: gradual-app-kill
  namespace: bank-of-anthos  # Ensure this matches your namespace
spec:
  entry: network-latency-sequence
  templates:
    - name: network-latency-sequence
      templateType: Serial  # Defines sequential execution
      children:
        - block-25ms-latency
        - block-50ms-latency
        - block-75ms-latency
        - block-100ms-latency
        - pod-restart-task  # Added the new pod restart task here
    - name: block-25ms-latency
      templateType: NetworkChaos
      networkChaos:
        action: delay
        mode: one
        selector:
          labelSelectors:
            statefulset.kubernetes.io/pod-name: ledger-db-0  # Matches the StatefulSet pod name
        delay:
          latency: "1200ms"
          correlation: "25"
          jitter: "0ms"
      deadline: "1m"  # Using deadline instead of duration
    - name: block-50ms-latency
      templateType: NetworkChaos
      networkChaos:
        action: delay
        mode: one
        selector:
          labelSelectors:
            statefulset.kubernetes.io/pod-name: ledger-db-0  # Matches the StatefulSet pod name
        delay:
          latency: "1500ms"
          correlation: "50"
          jitter: "0ms"
      deadline: "1m"
    - name: block-75ms-latency
      templateType: NetworkChaos
      networkChaos:
        action: delay
        mode: one
        selector:
          labelSelectors:
            statefulset.kubernetes.io/pod-name: ledger-db-0  # Matches the StatefulSet pod name
        delay:
          latency: "2000ms"
          correlation: "75"
          jitter: "0ms"
      deadline: "1m"
    - name: block-100ms-latency
      templateType: NetworkChaos
      networkChaos:
        action: delay
        mode: one
        selector:
          labelSelectors:
            statefulset.kubernetes.io/pod-name: ledger-db-0  # Matches the StatefulSet pod name
        delay:
          latency: "2500ms"
          correlation: "100"
          jitter: "0ms"
      deadline: "1m"
    - name: pod-restart-task  # New task for pod restart
      templateType: PodChaos
      podChaos:
        action: pod-kill
        mode: one
        selector:
          namespaces:
            - bank-of-anthos
          labelSelectors:
            statefulset.kubernetes.io/pod-name: ledger-db-0  # Matches the StatefulSet pod name
      deadline: "60s"  # Use deadline instead of duration

