apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: transactionhistory
  namespace: bank-of-anthos
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: transactionhistory # Deployment name
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80 # Target 50% CPU utilization
