apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos1
metadata:
  name: network-chaos
  namespace: ps
spec:
  action: partition
  mode: all
  selector:
    namespaces:
      - ps
    labelSelectors:
      app: postgres

